apiVersion: v1
kind: PersistentVolume
metadata:
  name: hpc-fss-pv
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: fss.csi.oraclecloud.com
    volumeHandle: ocid1.filesystem.oc1.iad.aaaa______j2xw:10.0.0.6:/HPC-FileSystem
    
    
    ocid1.filesystem.oc1.eu_frankfurt_1.aaaaaaaaaahka24vmzzgcllqojxwiotfouwwm4tbnzvwm5lsoqwtcllbmqwtcaaa:10.0.120.133/HPC_Filesystem